export const GET_CUSTOMERS_FROM_SERVER = 'GET_CUSTOMERS_FROM_SERVER';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_REAL = 'CREATE_CUSTOMER_REAL';
export const CREATE_CUSTOMER_UNDO = 'CREATE_CUSTOMER_UNDO';
// Serveris nepatvirtino sukurimo
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_REAL = 'DELETE_CUSTOMER_REAL';
export const DELETE_CUSTOMER_UNDO = 'DELETE_CUSTOMER_UNDO';
// Serveris nepatvirtino trinimo
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_REAL = 'UPDATE_CUSTOMER_REAL';
export const UPDATE_CUSTOMER_UNDO = 'UPDATE_CUSTOMER_UNDO';